### ISSUE TITLE
README should feature a photo

### ISSUE THREAD

**Issue by orta** [alloy/The-Jag#30]
and ideally if this is something that it going to improve visually over time, a collection of photos over time.

**Comment by alloy** [comment]
![front](https://cloud.githubusercontent.com/assets/2320/19019713/de35fc52-8890-11e6-9e92-e275eb71de0e.jpg)
![back](https://cloud.githubusercontent.com/assets/2320/19019715/df4017e0-8890-11e6-9ac6-64fd28dccf79.jpg)

**Comment by alloy** [comment]
Yeah, I should have taken photos over time… I suck at that, sorry

**Comment by orta** [comment]
Looks 💯

**Comment by alloy** [comment]
:bow:

Added photo of the renovated rims too.
